# Base Image
FROM continuumio/anaconda3

# Metadata
LABEL base.image="continuumio/anaconda3"
LABEL version="1"
LABEL software="rnaseq-dga"
LABEL software.version="0.0.1"
LABEL description=""
LABEL tags="RNASeq"
LABEL website="https://github.com/ncbi/pm4ngs"

# Maintainer
MAINTAINER Roberto Vera Alvarez <veraalva@ncbi.nlm.nih.gov>

USER root

RUN apt-get update && \
    apt-get install -y wget git parallel locales-all && \
    apt-get clean && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Updating Anaconda packages
RUN /opt/conda/bin/conda update conda
RUN /opt/conda/bin/conda update anaconda
RUN /opt/conda/bin/conda update --all
RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge

# Adding Bioconda packages
RUN wget -O /tmp/conda-jupyter.yaml https://raw.githubusercontent.com/ncbi/cwl-ngs-workflows-cbb/master/requirements/conda-jupyter.yaml
RUN /opt/conda/bin/conda env update -n base -f /tmp/conda-jupyter.yaml
RUN /opt/conda/bin/conda install -c bioconda galaxy-lib
RUN wget -O /tmp/conda-rnaseq.yaml https://raw.githubusercontent.com/ncbi/cwl-ngs-workflows-cbb/master/requirements/conda-rnaseq.yaml
RUN /opt/conda/bin/conda env create -f /tmp/conda-rnaseq.yaml
RUN rm -v /tmp/conda-jupyter.yaml /tmp/conda-rnaseq.yaml

# Add user ubuntu with no password, add to sudo group
RUN adduser --disabled-password --gecos '' ubuntu
RUN chmod a+rwx /home/ubuntu/
RUN chown -R ubuntu /home/ubuntu
USER ubuntu
RUN locale -a
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV HOME=/home/ubuntu
ENV PATH="/opt/conda/envs/rnaseq/bin:${PATH}"
WORKDIR /home/ubuntu
