name: Upload Python Package

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0             # fetch full history & tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      - name: Install version plugin
        # Ensure that poetry-dynamic-versioning plugin is available to Poetry CLI
        run: |
          poetry self add poetry-dynamic-versioning[plugin]

      - name: Build and publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish